trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true  # Isso mantém as credenciais do Git

  - script: |
      git config --global user.email "natthaliebohm@hotmail.com"
      git config --global user.name "Natthalie - Azure DevOps"
      git fetch origin
      git checkout FRONTEND_DEV  # Faz o checkout da branch DEV
      git checkout -b FRONTEND_QA  # -B força a recriação da branch QA
      git push origin FRONTEND_QA --force  # Força o push para FRONTEND_QA
    displayName: 'Forçar clone de FRONTEND_DEV para FRONTEND_QA'
