name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - FRONTEND_PROD
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - FRONTEND_PROD

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    env:
      CI: false  # Força o CI=false globalmente, garantindo que não trate warnings como erros
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: habituau-web
        run: yarn install

      - name: Build Application
        working-directory: habituau-web
        run: |
          CI=false yarn build  # Sobrescreve CI novamente para garantir que warnings não interrompam o build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_OCEAN_0F803990F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/habituau-web"
          output_location: "build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_OCEAN_0F803990F }}
          action: "close"
